org.gradle.jvmargs=-Xmx180m -XX:MaxMetaspaceSize=160m -XX:+UseSerialGC -XX:ReservedCodeCacheSize=24m -Xss512k
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configureondemand=true
org.gradle.caching=false
kotlin.daemon.jvmargs=-Xmx80m -XX:MaxMetaspaceSize=64m -Xss384k
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
